FROM golang:latest AS build-stage

WORKDIR /app

COPY go.mod go.sum ./
RUN go mod download
    
COPY app ./

RUN CGO_ENABLED=0 GOOS=linux go build -o /app

FROM build-stage AS test-stage
RUN go test -v ./..

# Smaller image
FROM gcr.io/distroless/base-debian11 AS build-release-stage

WORKDIR /

COPY --from=build-stage /app /app

EXPOSE 8080

USER root:root

ENTRYPOINT ["app"]